debug: false

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: loc
  jpa:
    hibernate:
      ddl-auto: update
      dialect: MySQLDialect
    database: MYSQL
    show-sql: false
    open-in-view: true
  application:
    admin:
      enabled: false

app:
  jwt:
    secret: RestauBot20232024tajeb

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure:
            logging: OFF
